# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mimic < Formula
  desc "Mimic is standalone HTTP-based mock server."
  homepage "https://github.com/enginyoyen/mimic"
  version "0.0.2"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/enginyoyen/mimic/releases/download/0.0.2/mimic_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "164b9d6991ad370ef2caca5e1b4b2c1f552e5223beb5673ac5f872d339f8136a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/enginyoyen/mimic/releases/download/0.0.2/mimic_0.0.2_Linux_x86_64.tar.gz"
    sha256 "13f1d1ccb489bc32fd1f1b7d156043758b0ca5178e6eacb7fa684128f0936fb3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/enginyoyen/mimic/releases/download/0.0.2/mimic_0.0.2_Linux_arm64.tar.gz"
    sha256 "be194e2bb23177870fb692184519d94251b88729b2f25a0bfcdf484226c2367f"
  end

  def install
    bin.install "mimic"
  end

  test do
    system "#{bin}/mimic --version"
  end
end
